#!/bin/bash

APPSERVER_TYPE="wildfly"
APPSERVER_VERSION="13.0.0.Final"
APPSERVER_DOWNLOAD_URL="http://download.jboss.org/$APPSERVER_TYPE/$APPSERVER_VERSION/$APPSERVER_TYPE-$APPSERVER_VERSION.zip"

LIFERAY_PREFIX="liferay-ce-portal"
LIFERAY_FULL_VERSION="7.1.0-ga1-20180703012531655"
LIFERAY_BASE_URL="https://sourceforge.net/projects/lportal/files/Liferay%20Portal/7.1.0%20GA1"

LIFERAY_HOME="/opt/liferay"
APPSERVER_HOME_PATH="/opt/$APPSERVER_TYPE"

LIFERAY_TURN_OFF_LOGGING="true"

JDBC_DRIVER_DOWNLOAD_URL="https://jdbc.postgresql.org/download/postgresql-42.2.4.jar"
JDBC_DRIVER_CLASSNAME="org.postgresql.Driver"
JDBC_DRIVER_CONNECTION_URL="jdbc:postgresql:ddd"
JDBC_DRIVER_USERNAME="postgres"
JDBC_DRIVER_PASSWORD="postgres"
JDBC_CREDENTIAL_STORE_PASSWORD="cs_pass"
